-- Content [ent6]
drop table "APP"."CONTENT";
-- Exercise [ent5]
drop table "APP"."EXERCISE";
-- Lesson [ent4]
drop table "APP"."LESSON";
-- Curriculum [ent3]
drop table "APP"."CURRICULUM";
-- Course [ent2]
drop table "APP"."COURSE";
-- Comment [ent14]
drop table "APP"."COMMENT";
-- Post [ent13]
drop table "APP"."POST";
-- Forum [ent12]
drop table "APP"."FORUM";
-- Support [ent1]
drop table "APP"."SUPPORT";
-- User [User]
drop table "APP"."USER";
-- Module [Module]
drop table "APP"."MODULE";
-- Group [Group]
drop table "APP"."GROUP";
